import ApiTargets from 'js/components/api_targets';
import NetworkWidget from 'js/widgets/network_vis/network_widget';

var options = {};

options.endpoint = ApiTargets.SERVICE_AUTHOR_NETWORK;

options.helpText =
  '<p>The circular graph shows you the main author groups within your results.' +
  'These groups are generated by a community detection algorithm, and their sizes represent the cumulative ' +
  'frequency of occurence in the result set of all their members. (In other words: people who ' +
  'co-author papers together appear in the same cluster.) Click on either a name or a group to' +
  'learn more about the papers by those particular authors. You can filter your current search results' +
  "by clicking the 'add to filter' button in the detail view. </p>";

options.networkType = 'author';

export default function() {
  return new NetworkWidget(options);
}
