'use strict';
/**
 * Options for the `concat` grunt task
 *
 * @module grunt/concat
 */
module.exports = function (grunt) {

  var paths = [
    [
      "discovery.config",
      "./discovery.config.js"
    ],
    [
      "js/apps/discovery/main",
      "./js/apps/discovery/main.js"
    ],
    [
      "config",
      "././discovery.config.js"
    ],
    [
      "router",
      "./js/apps/discovery/router.js"
    ],
    [
      "js/components/application",
      "./js/components/application.js"
    ],
    [
      "js/mixins/discovery_bootstrap",
      "./js/mixins/discovery_bootstrap.js"
    ],
    [
      "js/mixins/api_access",
      "./js/mixins/api_access.js"
    ],
    [
      "es5-shim",
      "//cdnjs.cloudflare.com/ajax/libs/es5-shim/4.5.10/es5-shim.min.js"
    ],
    [
      "discovery.vars",
      "./discovery.vars.js"
    ],
    [
      "hbs/handlebars",
      "./libs/require-handlebars-plugin/hbs/handlebars.js"
    ],
    [
      "google-analytics",
      "//google-analytics.com/analytics.js"
    ],
    [
      "underscore",
      "//cdnjs.cloudflare.com/ajax/libs/lodash.js/2.4.2/lodash.min.js"
    ],
    [
      "jquery",
      "//ajax.aspnetcdn.com/ajax/jQuery/jquery-2.0.3.min.js"
    ],
    [
      "js/components/api_query",
      "./js/components/api_query.js"
    ],
    [
      "js/mixins/dependon",
      "./js/mixins/dependon.js"
    ],
    [
      "js/components/api_feedback",
      "./js/components/api_feedback.js"
    ],
    [
      "js/components/api_request",
      "./js/components/api_request.js"
    ],
    [
      "js/components/api_targets",
      "./js/components/api_targets.js"
    ],
    [
      "js/components/api_query_updater",
      "./js/components/api_query_updater.js"
    ],
    [
      "js/components/beehive",
      "./js/components/beehive.js"
    ],
    [
      "js/components/pubsub_events",
      "./js/components/pubsub_events.js"
    ],
    [
      "hbs",
      "./libs/require-handlebars-plugin/hbs.js"
    ],
    [
      "d3",
      "//cdnjs.cloudflare.com/ajax/libs/d3/3.4.6/d3.min.js"
    ],
    [
      "js/components/solr_params",
      "./js/components/solr_params.js"
    ],
    [
      "js/components/facade",
      "./js/components/facade.js"
    ],
    [
      "js/components/pubsub_key",
      "./js/components/pubsub_key.js"
    ],
    [
      "js/mixins/hardened",
      "./js/mixins/hardened.js"
    ],
    [
      "js/components/default_request",
      "./js/components/default_request.js"
    ],
    [
      "js/components/generic_module",
      "./js/components/generic_module.js"
    ],
    [
      "js/components/services_container",
      "./js/components/services_container.js"
    ],
    [
      "hbs/underscore",
      "./libs/require-handlebars-plugin/hbs/underscore.js"
    ],
    [
      "hbs/json2",
      "./libs/require-handlebars-plugin/hbs/json2.js"
    ],
    [
      "js/components/multi_params",
      "./js/components/multi_params.js"
    ],
    [
      "backbone",
      "//cdnjs.cloudflare.com/ajax/libs/backbone.js/1.1.2/backbone-min.js"
    ],
    [
      "analytics",
      "./js/components/analytics.js"
    ],
    [
      "d3-cloud",
      "//cdnjs.cloudflare.com/ajax/libs/d3-cloud/1.2.5/d3.layout.cloud.min.js"
    ],
    [
      "backbone-validation",
      "//cdnjs.cloudflare.com/ajax/libs/backbone.validation/0.11.3/backbone-validation-amd-min.js"
    ],
    [
      "js/wraps/discovery_mediator",
      "./js/wraps/discovery_mediator.js"
    ],
    [
      "js/components/query_mediator",
      "./js/components/query_mediator.js"
    ],
    [
      "js/bugutils/diagnostics",
      "./js/bugutils/diagnostics.js"
    ],
    [
      "js/wraps/alerts_mediator",
      "./js/wraps/alerts_mediator.js"
    ],
    [
      "js/modules/orcid/module",
      "./js/modules/orcid/module.js"
    ],
    [
      "js/widgets/facet/factory",
      "./js/widgets/facet/factory.js"
    ],
    [
      "js/services/api",
      "./js/services/api.js"
    ],
    [
      "js/services/pubsub",
      "./js/services/pubsub.js"
    ],
    [
      "js/apps/discovery/navigator",
      "./js/apps/discovery/navigator.js"
    ],
    [
      "js/services/storage",
      "./js/services/storage.js"
    ],
    [
      "js/components/history_manager",
      "./js/components/history_manager.js"
    ],
    [
      "js/components/user",
      "./js/components/user.js"
    ],
    [
      "js/components/session",
      "./js/components/session.js"
    ],
    [
      "js/page_managers/master",
      "./js/page_managers/master.js"
    ],
    [
      "js/components/app_storage",
      "./js/components/app_storage.js"
    ],
    [
      "js/components/recaptcha_manager",
      "./js/components/recaptcha_manager.js"
    ],
    [
      "js/components/csrf_manager",
      "./js/components/csrf_manager.js"
    ],
    [
      "js/components/library_controller",
      "./js/components/library_controller.js"
    ],
    [
      "js/components/doc_stash_controller",
      "./js/components/doc_stash_controller.js"
    ],
    [
      "js/components/feedback_mediator",
      "./js/components/feedback_mediator.js"
    ],
    [
      "js/widgets/widget_states",
      "./js/widgets/widget_states.js"
    ],
    [
      "js/components/alerts",
      "./js/components/alerts.js"
    ],
    [
      "js/components/api_response",
      "./js/components/api_response.js"
    ],
    [
      "js/mixins/add_secondary_sort",
      "./js/mixins/add_secondary_sort.js"
    ],
    [
      "js/components/json_response",
      "./js/components/json_response.js"
    ],
    [
      "utils",
      "./js/utils.js"
    ],
    [
      "js/components/alerts_mediator",
      "./js/components/alerts_mediator.js"
    ],
    [
      "js/modules/orcid/orcid_api",
      "./js/modules/orcid/orcid_api.js"
    ],
    [
      "js/widgets/facet/widget",
      "./js/widgets/facet/widget.js"
    ],
    [
      "js/widgets/facet/graph-facet/widget",
      "./js/widgets/facet/graph-facet/widget.js"
    ],
    [
      "moment",
      "//cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.2/moment.min.js"
    ],
    [
      "js/services/default_pubsub",
      "./js/services/default_pubsub.js"
    ],
    [
      "js/components/navigator",
      "./js/components/navigator.js"
    ],
    [
      "js/components/persistent_storage",
      "./js/components/persistent_storage.js"
    ],
    [
      "js/widgets/base/base_widget",
      "./js/widgets/base/base_widget.js"
    ],
    [
      "js/page_managers/controller",
      "./js/page_managers/controller.js"
    ],
    [
      "cache",
      "./libs/dsjslib/lib/Cache.js"
    ],
    [
      "sprintf",
      "//cdnjs.cloudflare.com/ajax/libs/sprintf/1.0.2/sprintf.min.js"
    ],
    [
      "js/components/solr_response",
      "./js/components/solr_response.js"
    ],
    [
      "react",
      "//cdnjs.cloudflare.com/ajax/libs/react/15.6.1/react-with-addons.min.js"
    ],
    [
      "react-dom",
      "//cdnjs.cloudflare.com/ajax/libs/react/15.6.1/react-dom.min.js"
    ],
    [
      "react-redux",
      "//cdnjs.cloudflare.com/ajax/libs/react-redux/4.4.5/react-redux.min.js"
    ],
    [
      "es6",
      "./libs/requirejs-babel-plugin/es6.js"
    ],
    [
      "js/widgets/facet/actions",
      "./js/widgets/facet/actions.js"
    ],
    [
      "js/widgets/facet/reducers",
      "./js/widgets/facet/reducers.js"
    ],
    [
      "js/widgets/facet/create_store",
      "./js/widgets/facet/create_store.js"
    ],
    [
      "js/mixins/link_generator_mixin",
      "./js/mixins/link_generator_mixin.js"
    ],
    [
      "js/modules/orcid/work",
      "./js/modules/orcid/work.js"
    ],
    [
      "js/modules/orcid/profile",
      "./js/modules/orcid/profile.js"
    ],
    [
      "marionette",
      "//cdnjs.cloudflare.com/ajax/libs/backbone.marionette/2.4.5/backbone.marionette.min.js"
    ],
    [
      "js/components/transition",
      "./js/components/transition.js"
    ],
    [
      "js/components/transition_catalog",
      "./js/components/transition_catalog.js"
    ],
    [
      "js/mixins/widget_mixin_method",
      "./js/mixins/widget_mixin_method.js"
    ],
    [
      "js/mixins/widget_state_manager",
      "./js/mixins/widget_state_manager.js"
    ],
    [
      "js/page_managers/three_column_view",
      "./js/page_managers/three_column_view.js"
    ],
    [
      "js/page_managers/view_mixin",
      "./js/page_managers/view_mixin.js"
    ],
    [
      "babel",
      "./libs/requirejs-babel-plugin/babel-5.8.34.min.js"
    ],
    [
      "redux",
      "//cdnjs.cloudflare.com/ajax/libs/redux/3.5.2/redux.min.js"
    ],
    [
      "redux-thunk",
      "//cdnjs.cloudflare.com/ajax/libs/redux-thunk/2.1.0/redux-thunk.min.js"
    ],
    [
      "js/mixins/openurl_generator",
      "./js/mixins/openurl_generator.js"
    ],
    [
      "jsonpath",
      "//cdn.jsdelivr.net/npm/jsonpath@0.2.12/jsonpath.min.js"
    ],
    [
      "persist-js",
      "//cdn.jsdelivr.net/npm/persist-js@0.3.1/src/persist.min.js"
    ],
    [
      "js/mixins/widget_utility",
      "./js/mixins/widget_utility.js"
    ],
    [
      "jquery-ui",
      "//ajax.aspnetcdn.com/ajax/jquery.ui/1.10.4/jquery-ui.min.js"
    ],
    [
      "bootstrap",
      "//ajax.aspnetcdn.com/ajax/bootstrap/3.3.5/bootstrap.min.js"
    ],
    [
      "create-react-class",
      "//cdn.jsdelivr.net/npm/create-react-class@15.6.2/create-react-class.min.js"
    ],
    [
      "react-prop-types",
      "//cdnjs.cloudflare.com/ajax/libs/prop-types/15.6.0/prop-types.min.js"
    ],
    [
      "js/widgets/alerts/widget",
      "./js/widgets/alerts/widget.js"
    ],
    [
      "js/widgets/navbar/widget",
      "./js/widgets/navbar/widget.js"
    ],
    [
      "js/widgets/footer/widget",
      "./js/widgets/footer/widget.js"
    ],
    [
      "js/wraps/landing_page_manager/landing_page_manager",
      "./js/wraps/landing_page_manager/landing_page_manager.js"
    ],
    [
      "js/widgets/alerts/modal_view",
      "./js/widgets/alerts/modal_view.js"
    ],
    [
      "js/widgets/alerts/page_top_alert",
      "./js/widgets/alerts/page_top_alert.js"
    ],
    [
      "js/page_managers/toc_controller",
      "./js/page_managers/toc_controller.js"
    ],
    [
      "js/page_managers/one_column_view",
      "./js/page_managers/one_column_view.js"
    ],
    [
      "js/page_managers/toc_widget",
      "./js/page_managers/toc_widget.js"
    ],
    [
      "js/widgets/search_bar/search_bar_widget",
      "./js/widgets/search_bar/search_bar_widget.js"
    ],
    [
      "js/widgets/classic_form/widget",
      "./js/widgets/classic_form/widget.js"
    ],
    [
      "js/widgets/paper_search_form/widget",
      "./js/widgets/paper_search_form/widget.js"
    ],
    [
      "js/components/query_builder/plugin",
      "./js/components/query_builder/plugin.js"
    ],
    [
      "js/mixins/formatter",
      "./js/mixins/formatter.js"
    ],
    [
      "js/widgets/search_bar/autocomplete",
      "./js/widgets/search_bar/autocomplete.js"
    ],
    [
      "js/components/query_validator",
      "./js/components/query_validator.js"
    ],
    [
      "select2",
      "//cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.min.js"
    ],
    [
      "libs/select2/matcher",
      "./libs/select2/matcher.js"
    ],
    [
      "js/widgets/paper_search_form/topterms",
      "./js/widgets/paper_search_form/topterms.js"
    ],
    [
      "js/components/query_builder/rules_translator",
      "./js/components/query_builder/rules_translator.js"
    ],
    [
      "jquery-querybuilder",
      "./libs/jQuery-QueryBuilder/query-builder.js"
    ]
  ];
  var pathsByIds = paths.reduce(function (acc, p) {
    var key = p[1].replace('./', 'src/');
    acc[key] = p[0];
    return acc;
  }, {});

  return {
    options: {
      process: function (src, filepath) {
        console.log(pathsByIds[filepath]);
        return true;
      }
    },
    dist: {
      src: Object.keys(pathsByIds),
      dest: 'build/app.built.js'
    }
  };
};
