// GENERATED FILE (run grunt generate-require-config)

module.exports =
{
  "build": {
    "options": {
      "baseUrl": "src",
      "mainConfigFile": "src/discovery.config.js",
      "dir": "build",
      "optimize": "none",
      "paths": {
        "backbone-validation": "empty:",
        "backbone.stickit": "empty:",
        "backbone.wreqr": "empty:",
        "backbone": "empty:",
        "bootstrap": "empty:",
        "classnames": "empty:",
        "clipboard": "empty:",
        "create-react-class": "empty:",
        "d3-cloud": "empty:",
        "d3": "empty:",
        "es5-shim": "empty:",
        "filesaver": "empty:",
        "google-analytics": "empty:",
        "google-recaptcha": "empty:",
        "jquery-ui": "empty:",
        "jquery": "empty:",
        "jsonpath": "empty:",
        "marionette": "empty:",
        "mathjax": "empty:",
        "moment": "empty:",
        "persist-js": "empty:",
        "react-bootstrap": "empty:",
        "react-dom": "empty:",
        "react-prop-types": "empty:",
        "react-redux": "empty:",
        "react": "empty:",
        "redux-thunk": "empty:",
        "redux": "empty:",
        "requirejs": "empty:",
        "reselect": "empty:",
        "select2": "empty:",
        "sinon": "empty:",
        "sprintf": "empty:",
        "underscore": "empty:"
      }
    }
  },
  "common": {
    "options": {
      "logLevel": 1,
      "baseUrl": "build",
      "name": "common.bundle",
      "out": "build/common.bundle.js",
      "optimize": "none",
      "mainConfigFile": "build/app.config.js",
      "deps": [],
      "create": true,
      "include": [
        "config",
        "analytics",
        "router",
        "cache",
        "es6",
        "hbs",
        "immutable",
        "jquery-querybuilder",
        "redux-immutable",
        "utils"
      ],
      "paths": {
        "backbone-validation": "empty:",
        "backbone.stickit": "empty:",
        "backbone.wreqr": "empty:",
        "backbone": "empty:",
        "bootstrap": "empty:",
        "classnames": "empty:",
        "clipboard": "empty:",
        "create-react-class": "empty:",
        "d3-cloud": "empty:",
        "d3": "empty:",
        "es5-shim": "empty:",
        "filesaver": "empty:",
        "google-analytics": "empty:",
        "google-recaptcha": "empty:",
        "jquery-ui": "empty:",
        "jquery": "empty:",
        "jsonpath": "empty:",
        "marionette": "empty:",
        "mathjax": "empty:",
        "moment": "empty:",
        "persist-js": "empty:",
        "react-bootstrap": "empty:",
        "react-dom": "empty:",
        "react-prop-types": "empty:",
        "react-redux": "empty:",
        "react": "empty:",
        "redux-thunk": "empty:",
        "redux": "empty:",
        "requirejs": "empty:",
        "reselect": "empty:",
        "select2": "empty:",
        "sinon": "empty:",
        "sprintf": "empty:",
        "underscore": "empty:"
      }
    }
  },
  "core": {
    "options": {
      "logLevel": 1,
      "baseUrl": "build",
      "name": "core.bundle",
      "out": "build/core.bundle.js",
      "optimize": "none",
      "mainConfigFile": "build/app.config.js",
      "deps": [],
      "create": true,
      "include": [
        "js/wraps/discovery_mediator",
        "js/components/query_mediator",
        "js/bugutils/diagnostics",
        "js/wraps/alerts_mediator",
        "js/modules/orcid/module",
        "js/services/api",
        "js/services/pubsub",
        "js/apps/discovery/navigator",
        "js/services/storage",
        "js/components/history_manager",
        "js/components/user",
        "js/components/session",
        "discovery.vars",
        "js/page_managers/master",
        "js/components/app_storage",
        "js/components/recaptcha_manager",
        "js/components/csrf_manager",
        "js/components/library_controller",
        "js/components/doc_stash_controller",
        "js/widgets/facet/factory"
      ],
      "exclude": [
        "common.bundle"
      ],
      "paths": {
        "backbone-validation": "empty:",
        "backbone.stickit": "empty:",
        "backbone.wreqr": "empty:",
        "backbone": "empty:",
        "bootstrap": "empty:",
        "classnames": "empty:",
        "clipboard": "empty:",
        "create-react-class": "empty:",
        "d3-cloud": "empty:",
        "d3": "empty:",
        "es5-shim": "empty:",
        "filesaver": "empty:",
        "google-analytics": "empty:",
        "google-recaptcha": "empty:",
        "jquery-ui": "empty:",
        "jquery": "empty:",
        "jsonpath": "empty:",
        "marionette": "empty:",
        "mathjax": "empty:",
        "moment": "empty:",
        "persist-js": "empty:",
        "react-bootstrap": "empty:",
        "react-dom": "empty:",
        "react-prop-types": "empty:",
        "react-redux": "empty:",
        "react": "empty:",
        "redux-thunk": "empty:",
        "redux": "empty:",
        "requirejs": "empty:",
        "reselect": "empty:",
        "select2": "empty:",
        "sinon": "empty:",
        "sprintf": "empty:",
        "underscore": "empty:"
      }
    }
  },
  "abstract": {
    "options": {
      "logLevel": 1,
      "baseUrl": "build",
      "name": "abstract.bundle",
      "out": "build/abstract.bundle.js",
      "optimize": "none",
      "mainConfigFile": "build/app.config.js",
      "deps": [],
      "create": true,
      "include": [
        "js/widgets/abstract/widget"
      ],
      "exclude": [
        "common.bundle",
        "core.bundle"
      ],
      "paths": {
        "backbone-validation": "empty:",
        "backbone.stickit": "empty:",
        "backbone.wreqr": "empty:",
        "backbone": "empty:",
        "bootstrap": "empty:",
        "classnames": "empty:",
        "clipboard": "empty:",
        "create-react-class": "empty:",
        "d3-cloud": "empty:",
        "d3": "empty:",
        "es5-shim": "empty:",
        "filesaver": "empty:",
        "google-analytics": "empty:",
        "google-recaptcha": "empty:",
        "jquery-ui": "empty:",
        "jquery": "empty:",
        "jsonpath": "empty:",
        "marionette": "empty:",
        "mathjax": "empty:",
        "moment": "empty:",
        "persist-js": "empty:",
        "react-bootstrap": "empty:",
        "react-dom": "empty:",
        "react-prop-types": "empty:",
        "react-redux": "empty:",
        "react": "empty:",
        "redux-thunk": "empty:",
        "redux": "empty:",
        "requirejs": "empty:",
        "reselect": "empty:",
        "select2": "empty:",
        "sinon": "empty:",
        "sprintf": "empty:",
        "underscore": "empty:"
      }
    }
  },
  "alerts": {
    "options": {
      "logLevel": 1,
      "baseUrl": "build",
      "name": "alerts.bundle",
      "out": "build/alerts.bundle.js",
      "optimize": "none",
      "mainConfigFile": "build/app.config.js",
      "deps": [],
      "create": true,
      "include": [
        "js/widgets/alerts/widget"
      ],
      "exclude": [
        "common.bundle",
        "core.bundle"
      ],
      "paths": {
        "backbone-validation": "empty:",
        "backbone.stickit": "empty:",
        "backbone.wreqr": "empty:",
        "backbone": "empty:",
        "bootstrap": "empty:",
        "classnames": "empty:",
        "clipboard": "empty:",
        "create-react-class": "empty:",
        "d3-cloud": "empty:",
        "d3": "empty:",
        "es5-shim": "empty:",
        "filesaver": "empty:",
        "google-analytics": "empty:",
        "google-recaptcha": "empty:",
        "jquery-ui": "empty:",
        "jquery": "empty:",
        "jsonpath": "empty:",
        "marionette": "empty:",
        "mathjax": "empty:",
        "moment": "empty:",
        "persist-js": "empty:",
        "react-bootstrap": "empty:",
        "react-dom": "empty:",
        "react-prop-types": "empty:",
        "react-redux": "empty:",
        "react": "empty:",
        "redux-thunk": "empty:",
        "redux": "empty:",
        "requirejs": "empty:",
        "reselect": "empty:",
        "select2": "empty:",
        "sinon": "empty:",
        "sprintf": "empty:",
        "underscore": "empty:"
      }
    }
  },
  "api_query": {
    "options": {
      "logLevel": 1,
      "baseUrl": "build",
      "name": "api_query.bundle",
      "out": "build/api_query.bundle.js",
      "optimize": "none",
      "mainConfigFile": "build/app.config.js",
      "deps": [],
      "create": true,
      "include": [
        "js/widgets/api_query/widget"
      ],
      "exclude": [
        "common.bundle",
        "core.bundle"
      ],
      "paths": {
        "backbone-validation": "empty:",
        "backbone.stickit": "empty:",
        "backbone.wreqr": "empty:",
        "backbone": "empty:",
        "bootstrap": "empty:",
        "classnames": "empty:",
        "clipboard": "empty:",
        "create-react-class": "empty:",
        "d3-cloud": "empty:",
        "d3": "empty:",
        "es5-shim": "empty:",
        "filesaver": "empty:",
        "google-analytics": "empty:",
        "google-recaptcha": "empty:",
        "jquery-ui": "empty:",
        "jquery": "empty:",
        "jsonpath": "empty:",
        "marionette": "empty:",
        "mathjax": "empty:",
        "moment": "empty:",
        "persist-js": "empty:",
        "react-bootstrap": "empty:",
        "react-dom": "empty:",
        "react-prop-types": "empty:",
        "react-redux": "empty:",
        "react": "empty:",
        "redux-thunk": "empty:",
        "redux": "empty:",
        "requirejs": "empty:",
        "reselect": "empty:",
        "select2": "empty:",
        "sinon": "empty:",
        "sprintf": "empty:",
        "underscore": "empty:"
      }
    }
  },
  "api_request": {
    "options": {
      "logLevel": 1,
      "baseUrl": "build",
      "name": "api_request.bundle",
      "out": "build/api_request.bundle.js",
      "optimize": "none",
      "mainConfigFile": "build/app.config.js",
      "deps": [],
      "create": true,
      "include": [
        "js/widgets/api_request/widget"
      ],
      "exclude": [
        "common.bundle",
        "core.bundle"
      ],
      "paths": {
        "backbone-validation": "empty:",
        "backbone.stickit": "empty:",
        "backbone.wreqr": "empty:",
        "backbone": "empty:",
        "bootstrap": "empty:",
        "classnames": "empty:",
        "clipboard": "empty:",
        "create-react-class": "empty:",
        "d3-cloud": "empty:",
        "d3": "empty:",
        "es5-shim": "empty:",
        "filesaver": "empty:",
        "google-analytics": "empty:",
        "google-recaptcha": "empty:",
        "jquery-ui": "empty:",
        "jquery": "empty:",
        "jsonpath": "empty:",
        "marionette": "empty:",
        "mathjax": "empty:",
        "moment": "empty:",
        "persist-js": "empty:",
        "react-bootstrap": "empty:",
        "react-dom": "empty:",
        "react-prop-types": "empty:",
        "react-redux": "empty:",
        "react": "empty:",
        "redux-thunk": "empty:",
        "redux": "empty:",
        "requirejs": "empty:",
        "reselect": "empty:",
        "select2": "empty:",
        "sinon": "empty:",
        "sprintf": "empty:",
        "underscore": "empty:"
      }
    }
  },
  "api_response": {
    "options": {
      "logLevel": 1,
      "baseUrl": "build",
      "name": "api_response.bundle",
      "out": "build/api_response.bundle.js",
      "optimize": "none",
      "mainConfigFile": "build/app.config.js",
      "deps": [],
      "create": true,
      "include": [
        "js/widgets/api_response/widget"
      ],
      "exclude": [
        "common.bundle",
        "core.bundle"
      ],
      "paths": {
        "backbone-validation": "empty:",
        "backbone.stickit": "empty:",
        "backbone.wreqr": "empty:",
        "backbone": "empty:",
        "bootstrap": "empty:",
        "classnames": "empty:",
        "clipboard": "empty:",
        "create-react-class": "empty:",
        "d3-cloud": "empty:",
        "d3": "empty:",
        "es5-shim": "empty:",
        "filesaver": "empty:",
        "google-analytics": "empty:",
        "google-recaptcha": "empty:",
        "jquery-ui": "empty:",
        "jquery": "empty:",
        "jsonpath": "empty:",
        "marionette": "empty:",
        "mathjax": "empty:",
        "moment": "empty:",
        "persist-js": "empty:",
        "react-bootstrap": "empty:",
        "react-dom": "empty:",
        "react-prop-types": "empty:",
        "react-redux": "empty:",
        "react": "empty:",
        "redux-thunk": "empty:",
        "redux": "empty:",
        "requirejs": "empty:",
        "reselect": "empty:",
        "select2": "empty:",
        "sinon": "empty:",
        "sprintf": "empty:",
        "underscore": "empty:"
      }
    }
  },
  "associated": {
    "options": {
      "logLevel": 1,
      "baseUrl": "build",
      "name": "associated.bundle",
      "out": "build/associated.bundle.js",
      "optimize": "none",
      "mainConfigFile": "build/app.config.js",
      "deps": [],
      "create": true,
      "include": [
        "es6!js/widgets/associated/widget.jsx"
      ],
      "exclude": [
        "common.bundle",
        "core.bundle"
      ],
      "paths": {
        "backbone-validation": "empty:",
        "backbone.stickit": "empty:",
        "backbone.wreqr": "empty:",
        "backbone": "empty:",
        "bootstrap": "empty:",
        "classnames": "empty:",
        "clipboard": "empty:",
        "create-react-class": "empty:",
        "d3-cloud": "empty:",
        "d3": "empty:",
        "es5-shim": "empty:",
        "filesaver": "empty:",
        "google-analytics": "empty:",
        "google-recaptcha": "empty:",
        "jquery-ui": "empty:",
        "jquery": "empty:",
        "jsonpath": "empty:",
        "marionette": "empty:",
        "mathjax": "empty:",
        "moment": "empty:",
        "persist-js": "empty:",
        "react-bootstrap": "empty:",
        "react-dom": "empty:",
        "react-prop-types": "empty:",
        "react-redux": "empty:",
        "react": "empty:",
        "redux-thunk": "empty:",
        "redux": "empty:",
        "requirejs": "empty:",
        "reselect": "empty:",
        "select2": "empty:",
        "sinon": "empty:",
        "sprintf": "empty:",
        "underscore": "empty:"
      }
    }
  },
  "authentication": {
    "options": {
      "logLevel": 1,
      "baseUrl": "build",
      "name": "authentication.bundle",
      "out": "build/authentication.bundle.js",
      "optimize": "none",
      "mainConfigFile": "build/app.config.js",
      "deps": [],
      "create": true,
      "include": [
        "js/widgets/authentication/widget"
      ],
      "exclude": [
        "common.bundle",
        "core.bundle"
      ],
      "paths": {
        "backbone-validation": "empty:",
        "backbone.stickit": "empty:",
        "backbone.wreqr": "empty:",
        "backbone": "empty:",
        "bootstrap": "empty:",
        "classnames": "empty:",
        "clipboard": "empty:",
        "create-react-class": "empty:",
        "d3-cloud": "empty:",
        "d3": "empty:",
        "es5-shim": "empty:",
        "filesaver": "empty:",
        "google-analytics": "empty:",
        "google-recaptcha": "empty:",
        "jquery-ui": "empty:",
        "jquery": "empty:",
        "jsonpath": "empty:",
        "marionette": "empty:",
        "mathjax": "empty:",
        "moment": "empty:",
        "persist-js": "empty:",
        "react-bootstrap": "empty:",
        "react-dom": "empty:",
        "react-prop-types": "empty:",
        "react-redux": "empty:",
        "react": "empty:",
        "redux-thunk": "empty:",
        "redux": "empty:",
        "requirejs": "empty:",
        "reselect": "empty:",
        "select2": "empty:",
        "sinon": "empty:",
        "sprintf": "empty:",
        "underscore": "empty:"
      }
    }
  },
  "author_affiliation_tool": {
    "options": {
      "logLevel": 1,
      "baseUrl": "build",
      "name": "author_affiliation_tool.bundle",
      "out": "build/author_affiliation_tool.bundle.js",
      "optimize": "none",
      "mainConfigFile": "build/app.config.js",
      "deps": [],
      "create": true,
      "include": [
        "es6!js/widgets/author_affiliation_tool/widget.jsx"
      ],
      "exclude": [
        "common.bundle",
        "core.bundle"
      ],
      "paths": {
        "backbone-validation": "empty:",
        "backbone.stickit": "empty:",
        "backbone.wreqr": "empty:",
        "backbone": "empty:",
        "bootstrap": "empty:",
        "classnames": "empty:",
        "clipboard": "empty:",
        "create-react-class": "empty:",
        "d3-cloud": "empty:",
        "d3": "empty:",
        "es5-shim": "empty:",
        "filesaver": "empty:",
        "google-analytics": "empty:",
        "google-recaptcha": "empty:",
        "jquery-ui": "empty:",
        "jquery": "empty:",
        "jsonpath": "empty:",
        "marionette": "empty:",
        "mathjax": "empty:",
        "moment": "empty:",
        "persist-js": "empty:",
        "react-bootstrap": "empty:",
        "react-dom": "empty:",
        "react-prop-types": "empty:",
        "react-redux": "empty:",
        "react": "empty:",
        "redux-thunk": "empty:",
        "redux": "empty:",
        "requirejs": "empty:",
        "reselect": "empty:",
        "select2": "empty:",
        "sinon": "empty:",
        "sprintf": "empty:",
        "underscore": "empty:"
      }
    }
  },
  "breadcrumb": {
    "options": {
      "logLevel": 1,
      "baseUrl": "build",
      "name": "breadcrumb.bundle",
      "out": "build/breadcrumb.bundle.js",
      "optimize": "none",
      "mainConfigFile": "build/app.config.js",
      "deps": [],
      "create": true,
      "include": [
        "js/widgets/breadcrumb/widget"
      ],
      "exclude": [
        "common.bundle",
        "core.bundle"
      ],
      "paths": {
        "backbone-validation": "empty:",
        "backbone.stickit": "empty:",
        "backbone.wreqr": "empty:",
        "backbone": "empty:",
        "bootstrap": "empty:",
        "classnames": "empty:",
        "clipboard": "empty:",
        "create-react-class": "empty:",
        "d3-cloud": "empty:",
        "d3": "empty:",
        "es5-shim": "empty:",
        "filesaver": "empty:",
        "google-analytics": "empty:",
        "google-recaptcha": "empty:",
        "jquery-ui": "empty:",
        "jquery": "empty:",
        "jsonpath": "empty:",
        "marionette": "empty:",
        "mathjax": "empty:",
        "moment": "empty:",
        "persist-js": "empty:",
        "react-bootstrap": "empty:",
        "react-dom": "empty:",
        "react-prop-types": "empty:",
        "react-redux": "empty:",
        "react": "empty:",
        "redux-thunk": "empty:",
        "redux": "empty:",
        "requirejs": "empty:",
        "reselect": "empty:",
        "select2": "empty:",
        "sinon": "empty:",
        "sprintf": "empty:",
        "underscore": "empty:"
      }
    }
  },
  "bubble_chart": {
    "options": {
      "logLevel": 1,
      "baseUrl": "build",
      "name": "bubble_chart.bundle",
      "out": "build/bubble_chart.bundle.js",
      "optimize": "none",
      "mainConfigFile": "build/app.config.js",
      "deps": [],
      "create": true,
      "include": [
        "js/widgets/bubble_chart/widget"
      ],
      "exclude": [
        "common.bundle",
        "core.bundle"
      ],
      "paths": {
        "backbone-validation": "empty:",
        "backbone.stickit": "empty:",
        "backbone.wreqr": "empty:",
        "backbone": "empty:",
        "bootstrap": "empty:",
        "classnames": "empty:",
        "clipboard": "empty:",
        "create-react-class": "empty:",
        "d3-cloud": "empty:",
        "d3": "empty:",
        "es5-shim": "empty:",
        "filesaver": "empty:",
        "google-analytics": "empty:",
        "google-recaptcha": "empty:",
        "jquery-ui": "empty:",
        "jquery": "empty:",
        "jsonpath": "empty:",
        "marionette": "empty:",
        "mathjax": "empty:",
        "moment": "empty:",
        "persist-js": "empty:",
        "react-bootstrap": "empty:",
        "react-dom": "empty:",
        "react-prop-types": "empty:",
        "react-redux": "empty:",
        "react": "empty:",
        "redux-thunk": "empty:",
        "redux": "empty:",
        "requirejs": "empty:",
        "reselect": "empty:",
        "select2": "empty:",
        "sinon": "empty:",
        "sprintf": "empty:",
        "underscore": "empty:"
      }
    }
  },
  "citation_helper": {
    "options": {
      "logLevel": 1,
      "baseUrl": "build",
      "name": "citation_helper.bundle",
      "out": "build/citation_helper.bundle.js",
      "optimize": "none",
      "mainConfigFile": "build/app.config.js",
      "deps": [],
      "create": true,
      "include": [
        "js/widgets/citation_helper/widget"
      ],
      "exclude": [
        "common.bundle",
        "core.bundle"
      ],
      "paths": {
        "backbone-validation": "empty:",
        "backbone.stickit": "empty:",
        "backbone.wreqr": "empty:",
        "backbone": "empty:",
        "bootstrap": "empty:",
        "classnames": "empty:",
        "clipboard": "empty:",
        "create-react-class": "empty:",
        "d3-cloud": "empty:",
        "d3": "empty:",
        "es5-shim": "empty:",
        "filesaver": "empty:",
        "google-analytics": "empty:",
        "google-recaptcha": "empty:",
        "jquery-ui": "empty:",
        "jquery": "empty:",
        "jsonpath": "empty:",
        "marionette": "empty:",
        "mathjax": "empty:",
        "moment": "empty:",
        "persist-js": "empty:",
        "react-bootstrap": "empty:",
        "react-dom": "empty:",
        "react-prop-types": "empty:",
        "react-redux": "empty:",
        "react": "empty:",
        "redux-thunk": "empty:",
        "redux": "empty:",
        "requirejs": "empty:",
        "reselect": "empty:",
        "select2": "empty:",
        "sinon": "empty:",
        "sprintf": "empty:",
        "underscore": "empty:"
      }
    }
  },
  "classic_form": {
    "options": {
      "logLevel": 1,
      "baseUrl": "build",
      "name": "classic_form.bundle",
      "out": "build/classic_form.bundle.js",
      "optimize": "none",
      "mainConfigFile": "build/app.config.js",
      "deps": [],
      "create": true,
      "include": [
        "js/widgets/classic_form/widget"
      ],
      "exclude": [
        "common.bundle",
        "core.bundle"
      ],
      "paths": {
        "backbone-validation": "empty:",
        "backbone.stickit": "empty:",
        "backbone.wreqr": "empty:",
        "backbone": "empty:",
        "bootstrap": "empty:",
        "classnames": "empty:",
        "clipboard": "empty:",
        "create-react-class": "empty:",
        "d3-cloud": "empty:",
        "d3": "empty:",
        "es5-shim": "empty:",
        "filesaver": "empty:",
        "google-analytics": "empty:",
        "google-recaptcha": "empty:",
        "jquery-ui": "empty:",
        "jquery": "empty:",
        "jsonpath": "empty:",
        "marionette": "empty:",
        "mathjax": "empty:",
        "moment": "empty:",
        "persist-js": "empty:",
        "react-bootstrap": "empty:",
        "react-dom": "empty:",
        "react-prop-types": "empty:",
        "react-redux": "empty:",
        "react": "empty:",
        "redux-thunk": "empty:",
        "redux": "empty:",
        "requirejs": "empty:",
        "reselect": "empty:",
        "select2": "empty:",
        "sinon": "empty:",
        "sprintf": "empty:",
        "underscore": "empty:"
      }
    }
  },
  "dropdown-menu": {
    "options": {
      "logLevel": 1,
      "baseUrl": "build",
      "name": "dropdown-menu.bundle",
      "out": "build/dropdown-menu.bundle.js",
      "optimize": "none",
      "mainConfigFile": "build/app.config.js",
      "deps": [],
      "create": true,
      "include": [
        "js/widgets/dropdown-menu/widget"
      ],
      "exclude": [
        "common.bundle",
        "core.bundle"
      ],
      "paths": {
        "backbone-validation": "empty:",
        "backbone.stickit": "empty:",
        "backbone.wreqr": "empty:",
        "backbone": "empty:",
        "bootstrap": "empty:",
        "classnames": "empty:",
        "clipboard": "empty:",
        "create-react-class": "empty:",
        "d3-cloud": "empty:",
        "d3": "empty:",
        "es5-shim": "empty:",
        "filesaver": "empty:",
        "google-analytics": "empty:",
        "google-recaptcha": "empty:",
        "jquery-ui": "empty:",
        "jquery": "empty:",
        "jsonpath": "empty:",
        "marionette": "empty:",
        "mathjax": "empty:",
        "moment": "empty:",
        "persist-js": "empty:",
        "react-bootstrap": "empty:",
        "react-dom": "empty:",
        "react-prop-types": "empty:",
        "react-redux": "empty:",
        "react": "empty:",
        "redux-thunk": "empty:",
        "redux": "empty:",
        "requirejs": "empty:",
        "reselect": "empty:",
        "select2": "empty:",
        "sinon": "empty:",
        "sprintf": "empty:",
        "underscore": "empty:"
      }
    }
  },
  "export": {
    "options": {
      "logLevel": 1,
      "baseUrl": "build",
      "name": "export.bundle",
      "out": "build/export.bundle.js",
      "optimize": "none",
      "mainConfigFile": "build/app.config.js",
      "deps": [],
      "create": true,
      "include": [
        "es6!js/widgets/export/widget.jsx"
      ],
      "exclude": [
        "common.bundle",
        "core.bundle"
      ],
      "paths": {
        "backbone-validation": "empty:",
        "backbone.stickit": "empty:",
        "backbone.wreqr": "empty:",
        "backbone": "empty:",
        "bootstrap": "empty:",
        "classnames": "empty:",
        "clipboard": "empty:",
        "create-react-class": "empty:",
        "d3-cloud": "empty:",
        "d3": "empty:",
        "es5-shim": "empty:",
        "filesaver": "empty:",
        "google-analytics": "empty:",
        "google-recaptcha": "empty:",
        "jquery-ui": "empty:",
        "jquery": "empty:",
        "jsonpath": "empty:",
        "marionette": "empty:",
        "mathjax": "empty:",
        "moment": "empty:",
        "persist-js": "empty:",
        "react-bootstrap": "empty:",
        "react-dom": "empty:",
        "react-prop-types": "empty:",
        "react-redux": "empty:",
        "react": "empty:",
        "redux-thunk": "empty:",
        "redux": "empty:",
        "requirejs": "empty:",
        "reselect": "empty:",
        "select2": "empty:",
        "sinon": "empty:",
        "sprintf": "empty:",
        "underscore": "empty:"
      }
    }
  },
  "facet": {
    "options": {
      "logLevel": 1,
      "baseUrl": "build",
      "name": "facet.bundle",
      "out": "build/facet.bundle.js",
      "optimize": "none",
      "mainConfigFile": "build/app.config.js",
      "deps": [],
      "create": true,
      "include": [
        "js/widgets/facet/widget"
      ],
      "exclude": [
        "common.bundle",
        "core.bundle"
      ],
      "paths": {
        "backbone-validation": "empty:",
        "backbone.stickit": "empty:",
        "backbone.wreqr": "empty:",
        "backbone": "empty:",
        "bootstrap": "empty:",
        "classnames": "empty:",
        "clipboard": "empty:",
        "create-react-class": "empty:",
        "d3-cloud": "empty:",
        "d3": "empty:",
        "es5-shim": "empty:",
        "filesaver": "empty:",
        "google-analytics": "empty:",
        "google-recaptcha": "empty:",
        "jquery-ui": "empty:",
        "jquery": "empty:",
        "jsonpath": "empty:",
        "marionette": "empty:",
        "mathjax": "empty:",
        "moment": "empty:",
        "persist-js": "empty:",
        "react-bootstrap": "empty:",
        "react-dom": "empty:",
        "react-prop-types": "empty:",
        "react-redux": "empty:",
        "react": "empty:",
        "redux-thunk": "empty:",
        "redux": "empty:",
        "requirejs": "empty:",
        "reselect": "empty:",
        "select2": "empty:",
        "sinon": "empty:",
        "sprintf": "empty:",
        "underscore": "empty:"
      }
    }
  },
  "filter_visualizer": {
    "options": {
      "logLevel": 1,
      "baseUrl": "build",
      "name": "filter_visualizer.bundle",
      "out": "build/filter_visualizer.bundle.js",
      "optimize": "none",
      "mainConfigFile": "build/app.config.js",
      "deps": [],
      "create": true,
      "include": [
        "js/widgets/filter_visualizer/widget"
      ],
      "exclude": [
        "common.bundle",
        "core.bundle"
      ],
      "paths": {
        "backbone-validation": "empty:",
        "backbone.stickit": "empty:",
        "backbone.wreqr": "empty:",
        "backbone": "empty:",
        "bootstrap": "empty:",
        "classnames": "empty:",
        "clipboard": "empty:",
        "create-react-class": "empty:",
        "d3-cloud": "empty:",
        "d3": "empty:",
        "es5-shim": "empty:",
        "filesaver": "empty:",
        "google-analytics": "empty:",
        "google-recaptcha": "empty:",
        "jquery-ui": "empty:",
        "jquery": "empty:",
        "jsonpath": "empty:",
        "marionette": "empty:",
        "mathjax": "empty:",
        "moment": "empty:",
        "persist-js": "empty:",
        "react-bootstrap": "empty:",
        "react-dom": "empty:",
        "react-prop-types": "empty:",
        "react-redux": "empty:",
        "react": "empty:",
        "redux-thunk": "empty:",
        "redux": "empty:",
        "requirejs": "empty:",
        "reselect": "empty:",
        "select2": "empty:",
        "sinon": "empty:",
        "sprintf": "empty:",
        "underscore": "empty:"
      }
    }
  },
  "footer": {
    "options": {
      "logLevel": 1,
      "baseUrl": "build",
      "name": "footer.bundle",
      "out": "build/footer.bundle.js",
      "optimize": "none",
      "mainConfigFile": "build/app.config.js",
      "deps": [],
      "create": true,
      "include": [
        "js/widgets/footer/widget"
      ],
      "exclude": [
        "common.bundle",
        "core.bundle"
      ],
      "paths": {
        "backbone-validation": "empty:",
        "backbone.stickit": "empty:",
        "backbone.wreqr": "empty:",
        "backbone": "empty:",
        "bootstrap": "empty:",
        "classnames": "empty:",
        "clipboard": "empty:",
        "create-react-class": "empty:",
        "d3-cloud": "empty:",
        "d3": "empty:",
        "es5-shim": "empty:",
        "filesaver": "empty:",
        "google-analytics": "empty:",
        "google-recaptcha": "empty:",
        "jquery-ui": "empty:",
        "jquery": "empty:",
        "jsonpath": "empty:",
        "marionette": "empty:",
        "mathjax": "empty:",
        "moment": "empty:",
        "persist-js": "empty:",
        "react-bootstrap": "empty:",
        "react-dom": "empty:",
        "react-prop-types": "empty:",
        "react-redux": "empty:",
        "react": "empty:",
        "redux-thunk": "empty:",
        "redux": "empty:",
        "requirejs": "empty:",
        "reselect": "empty:",
        "select2": "empty:",
        "sinon": "empty:",
        "sprintf": "empty:",
        "underscore": "empty:"
      }
    }
  },
  "graphics": {
    "options": {
      "logLevel": 1,
      "baseUrl": "build",
      "name": "graphics.bundle",
      "out": "build/graphics.bundle.js",
      "optimize": "none",
      "mainConfigFile": "build/app.config.js",
      "deps": [],
      "create": true,
      "include": [
        "js/widgets/graphics/widget"
      ],
      "exclude": [
        "common.bundle",
        "core.bundle"
      ],
      "paths": {
        "backbone-validation": "empty:",
        "backbone.stickit": "empty:",
        "backbone.wreqr": "empty:",
        "backbone": "empty:",
        "bootstrap": "empty:",
        "classnames": "empty:",
        "clipboard": "empty:",
        "create-react-class": "empty:",
        "d3-cloud": "empty:",
        "d3": "empty:",
        "es5-shim": "empty:",
        "filesaver": "empty:",
        "google-analytics": "empty:",
        "google-recaptcha": "empty:",
        "jquery-ui": "empty:",
        "jquery": "empty:",
        "jsonpath": "empty:",
        "marionette": "empty:",
        "mathjax": "empty:",
        "moment": "empty:",
        "persist-js": "empty:",
        "react-bootstrap": "empty:",
        "react-dom": "empty:",
        "react-prop-types": "empty:",
        "react-redux": "empty:",
        "react": "empty:",
        "redux-thunk": "empty:",
        "redux": "empty:",
        "requirejs": "empty:",
        "reselect": "empty:",
        "select2": "empty:",
        "sinon": "empty:",
        "sprintf": "empty:",
        "underscore": "empty:"
      }
    }
  },
  "green_button": {
    "options": {
      "logLevel": 1,
      "baseUrl": "build",
      "name": "green_button.bundle",
      "out": "build/green_button.bundle.js",
      "optimize": "none",
      "mainConfigFile": "build/app.config.js",
      "deps": [],
      "create": true,
      "include": [
        "js/widgets/green_button/widget"
      ],
      "exclude": [
        "common.bundle",
        "core.bundle"
      ],
      "paths": {
        "backbone-validation": "empty:",
        "backbone.stickit": "empty:",
        "backbone.wreqr": "empty:",
        "backbone": "empty:",
        "bootstrap": "empty:",
        "classnames": "empty:",
        "clipboard": "empty:",
        "create-react-class": "empty:",
        "d3-cloud": "empty:",
        "d3": "empty:",
        "es5-shim": "empty:",
        "filesaver": "empty:",
        "google-analytics": "empty:",
        "google-recaptcha": "empty:",
        "jquery-ui": "empty:",
        "jquery": "empty:",
        "jsonpath": "empty:",
        "marionette": "empty:",
        "mathjax": "empty:",
        "moment": "empty:",
        "persist-js": "empty:",
        "react-bootstrap": "empty:",
        "react-dom": "empty:",
        "react-prop-types": "empty:",
        "react-redux": "empty:",
        "react": "empty:",
        "redux-thunk": "empty:",
        "redux": "empty:",
        "requirejs": "empty:",
        "reselect": "empty:",
        "select2": "empty:",
        "sinon": "empty:",
        "sprintf": "empty:",
        "underscore": "empty:"
      }
    }
  },
  "libraries_all": {
    "options": {
      "logLevel": 1,
      "baseUrl": "build",
      "name": "libraries_all.bundle",
      "out": "build/libraries_all.bundle.js",
      "optimize": "none",
      "mainConfigFile": "build/app.config.js",
      "deps": [],
      "create": true,
      "include": [
        "js/widgets/libraries_all/widget"
      ],
      "exclude": [
        "common.bundle",
        "core.bundle"
      ],
      "paths": {
        "backbone-validation": "empty:",
        "backbone.stickit": "empty:",
        "backbone.wreqr": "empty:",
        "backbone": "empty:",
        "bootstrap": "empty:",
        "classnames": "empty:",
        "clipboard": "empty:",
        "create-react-class": "empty:",
        "d3-cloud": "empty:",
        "d3": "empty:",
        "es5-shim": "empty:",
        "filesaver": "empty:",
        "google-analytics": "empty:",
        "google-recaptcha": "empty:",
        "jquery-ui": "empty:",
        "jquery": "empty:",
        "jsonpath": "empty:",
        "marionette": "empty:",
        "mathjax": "empty:",
        "moment": "empty:",
        "persist-js": "empty:",
        "react-bootstrap": "empty:",
        "react-dom": "empty:",
        "react-prop-types": "empty:",
        "react-redux": "empty:",
        "react": "empty:",
        "redux-thunk": "empty:",
        "redux": "empty:",
        "requirejs": "empty:",
        "reselect": "empty:",
        "select2": "empty:",
        "sinon": "empty:",
        "sprintf": "empty:",
        "underscore": "empty:"
      }
    }
  },
  "library_import": {
    "options": {
      "logLevel": 1,
      "baseUrl": "build",
      "name": "library_import.bundle",
      "out": "build/library_import.bundle.js",
      "optimize": "none",
      "mainConfigFile": "build/app.config.js",
      "deps": [],
      "create": true,
      "include": [
        "js/widgets/library_import/widget"
      ],
      "exclude": [
        "common.bundle",
        "core.bundle"
      ],
      "paths": {
        "backbone-validation": "empty:",
        "backbone.stickit": "empty:",
        "backbone.wreqr": "empty:",
        "backbone": "empty:",
        "bootstrap": "empty:",
        "classnames": "empty:",
        "clipboard": "empty:",
        "create-react-class": "empty:",
        "d3-cloud": "empty:",
        "d3": "empty:",
        "es5-shim": "empty:",
        "filesaver": "empty:",
        "google-analytics": "empty:",
        "google-recaptcha": "empty:",
        "jquery-ui": "empty:",
        "jquery": "empty:",
        "jsonpath": "empty:",
        "marionette": "empty:",
        "mathjax": "empty:",
        "moment": "empty:",
        "persist-js": "empty:",
        "react-bootstrap": "empty:",
        "react-dom": "empty:",
        "react-prop-types": "empty:",
        "react-redux": "empty:",
        "react": "empty:",
        "redux-thunk": "empty:",
        "redux": "empty:",
        "requirejs": "empty:",
        "reselect": "empty:",
        "select2": "empty:",
        "sinon": "empty:",
        "sprintf": "empty:",
        "underscore": "empty:"
      }
    }
  },
  "library_individual": {
    "options": {
      "logLevel": 1,
      "baseUrl": "build",
      "name": "library_individual.bundle",
      "out": "build/library_individual.bundle.js",
      "optimize": "none",
      "mainConfigFile": "build/app.config.js",
      "deps": [],
      "create": true,
      "include": [
        "js/widgets/library_individual/widget"
      ],
      "exclude": [
        "common.bundle",
        "core.bundle"
      ],
      "paths": {
        "backbone-validation": "empty:",
        "backbone.stickit": "empty:",
        "backbone.wreqr": "empty:",
        "backbone": "empty:",
        "bootstrap": "empty:",
        "classnames": "empty:",
        "clipboard": "empty:",
        "create-react-class": "empty:",
        "d3-cloud": "empty:",
        "d3": "empty:",
        "es5-shim": "empty:",
        "filesaver": "empty:",
        "google-analytics": "empty:",
        "google-recaptcha": "empty:",
        "jquery-ui": "empty:",
        "jquery": "empty:",
        "jsonpath": "empty:",
        "marionette": "empty:",
        "mathjax": "empty:",
        "moment": "empty:",
        "persist-js": "empty:",
        "react-bootstrap": "empty:",
        "react-dom": "empty:",
        "react-prop-types": "empty:",
        "react-redux": "empty:",
        "react": "empty:",
        "redux-thunk": "empty:",
        "redux": "empty:",
        "requirejs": "empty:",
        "reselect": "empty:",
        "select2": "empty:",
        "sinon": "empty:",
        "sprintf": "empty:",
        "underscore": "empty:"
      }
    }
  },
  "library_list": {
    "options": {
      "logLevel": 1,
      "baseUrl": "build",
      "name": "library_list.bundle",
      "out": "build/library_list.bundle.js",
      "optimize": "none",
      "mainConfigFile": "build/app.config.js",
      "deps": [],
      "create": true,
      "include": [
        "js/widgets/library_list/widget"
      ],
      "exclude": [
        "common.bundle",
        "core.bundle"
      ],
      "paths": {
        "backbone-validation": "empty:",
        "backbone.stickit": "empty:",
        "backbone.wreqr": "empty:",
        "backbone": "empty:",
        "bootstrap": "empty:",
        "classnames": "empty:",
        "clipboard": "empty:",
        "create-react-class": "empty:",
        "d3-cloud": "empty:",
        "d3": "empty:",
        "es5-shim": "empty:",
        "filesaver": "empty:",
        "google-analytics": "empty:",
        "google-recaptcha": "empty:",
        "jquery-ui": "empty:",
        "jquery": "empty:",
        "jsonpath": "empty:",
        "marionette": "empty:",
        "mathjax": "empty:",
        "moment": "empty:",
        "persist-js": "empty:",
        "react-bootstrap": "empty:",
        "react-dom": "empty:",
        "react-prop-types": "empty:",
        "react-redux": "empty:",
        "react": "empty:",
        "redux-thunk": "empty:",
        "redux": "empty:",
        "requirejs": "empty:",
        "reselect": "empty:",
        "select2": "empty:",
        "sinon": "empty:",
        "sprintf": "empty:",
        "underscore": "empty:"
      }
    }
  },
  "list_of_things": {
    "options": {
      "logLevel": 1,
      "baseUrl": "build",
      "name": "list_of_things.bundle",
      "out": "build/list_of_things.bundle.js",
      "optimize": "none",
      "mainConfigFile": "build/app.config.js",
      "deps": [],
      "create": true,
      "include": [
        "js/widgets/list_of_things/widget"
      ],
      "exclude": [
        "common.bundle",
        "core.bundle"
      ],
      "paths": {
        "backbone-validation": "empty:",
        "backbone.stickit": "empty:",
        "backbone.wreqr": "empty:",
        "backbone": "empty:",
        "bootstrap": "empty:",
        "classnames": "empty:",
        "clipboard": "empty:",
        "create-react-class": "empty:",
        "d3-cloud": "empty:",
        "d3": "empty:",
        "es5-shim": "empty:",
        "filesaver": "empty:",
        "google-analytics": "empty:",
        "google-recaptcha": "empty:",
        "jquery-ui": "empty:",
        "jquery": "empty:",
        "jsonpath": "empty:",
        "marionette": "empty:",
        "mathjax": "empty:",
        "moment": "empty:",
        "persist-js": "empty:",
        "react-bootstrap": "empty:",
        "react-dom": "empty:",
        "react-prop-types": "empty:",
        "react-redux": "empty:",
        "react": "empty:",
        "redux-thunk": "empty:",
        "redux": "empty:",
        "requirejs": "empty:",
        "reselect": "empty:",
        "select2": "empty:",
        "sinon": "empty:",
        "sprintf": "empty:",
        "underscore": "empty:"
      }
    }
  },
  "loading": {
    "options": {
      "logLevel": 1,
      "baseUrl": "build",
      "name": "loading.bundle",
      "out": "build/loading.bundle.js",
      "optimize": "none",
      "mainConfigFile": "build/app.config.js",
      "deps": [],
      "create": true,
      "include": [
        "js/widgets/loading/widget"
      ],
      "exclude": [
        "common.bundle",
        "core.bundle"
      ],
      "paths": {
        "backbone-validation": "empty:",
        "backbone.stickit": "empty:",
        "backbone.wreqr": "empty:",
        "backbone": "empty:",
        "bootstrap": "empty:",
        "classnames": "empty:",
        "clipboard": "empty:",
        "create-react-class": "empty:",
        "d3-cloud": "empty:",
        "d3": "empty:",
        "es5-shim": "empty:",
        "filesaver": "empty:",
        "google-analytics": "empty:",
        "google-recaptcha": "empty:",
        "jquery-ui": "empty:",
        "jquery": "empty:",
        "jsonpath": "empty:",
        "marionette": "empty:",
        "mathjax": "empty:",
        "moment": "empty:",
        "persist-js": "empty:",
        "react-bootstrap": "empty:",
        "react-dom": "empty:",
        "react-prop-types": "empty:",
        "react-redux": "empty:",
        "react": "empty:",
        "redux-thunk": "empty:",
        "redux": "empty:",
        "requirejs": "empty:",
        "reselect": "empty:",
        "select2": "empty:",
        "sinon": "empty:",
        "sprintf": "empty:",
        "underscore": "empty:"
      }
    }
  },
  "meta_tags": {
    "options": {
      "logLevel": 1,
      "baseUrl": "build",
      "name": "meta_tags.bundle",
      "out": "build/meta_tags.bundle.js",
      "optimize": "none",
      "mainConfigFile": "build/app.config.js",
      "deps": [],
      "create": true,
      "include": [
        "js/widgets/meta_tags/widget"
      ],
      "exclude": [
        "common.bundle",
        "core.bundle"
      ],
      "paths": {
        "backbone-validation": "empty:",
        "backbone.stickit": "empty:",
        "backbone.wreqr": "empty:",
        "backbone": "empty:",
        "bootstrap": "empty:",
        "classnames": "empty:",
        "clipboard": "empty:",
        "create-react-class": "empty:",
        "d3-cloud": "empty:",
        "d3": "empty:",
        "es5-shim": "empty:",
        "filesaver": "empty:",
        "google-analytics": "empty:",
        "google-recaptcha": "empty:",
        "jquery-ui": "empty:",
        "jquery": "empty:",
        "jsonpath": "empty:",
        "marionette": "empty:",
        "mathjax": "empty:",
        "moment": "empty:",
        "persist-js": "empty:",
        "react-bootstrap": "empty:",
        "react-dom": "empty:",
        "react-prop-types": "empty:",
        "react-redux": "empty:",
        "react": "empty:",
        "redux-thunk": "empty:",
        "redux": "empty:",
        "requirejs": "empty:",
        "reselect": "empty:",
        "select2": "empty:",
        "sinon": "empty:",
        "sprintf": "empty:",
        "underscore": "empty:"
      }
    }
  },
  "metrics": {
    "options": {
      "logLevel": 1,
      "baseUrl": "build",
      "name": "metrics.bundle",
      "out": "build/metrics.bundle.js",
      "optimize": "none",
      "mainConfigFile": "build/app.config.js",
      "deps": [],
      "create": true,
      "include": [
        "js/widgets/metrics/widget"
      ],
      "exclude": [
        "common.bundle",
        "core.bundle"
      ],
      "paths": {
        "backbone-validation": "empty:",
        "backbone.stickit": "empty:",
        "backbone.wreqr": "empty:",
        "backbone": "empty:",
        "bootstrap": "empty:",
        "classnames": "empty:",
        "clipboard": "empty:",
        "create-react-class": "empty:",
        "d3-cloud": "empty:",
        "d3": "empty:",
        "es5-shim": "empty:",
        "filesaver": "empty:",
        "google-analytics": "empty:",
        "google-recaptcha": "empty:",
        "jquery-ui": "empty:",
        "jquery": "empty:",
        "jsonpath": "empty:",
        "marionette": "empty:",
        "mathjax": "empty:",
        "moment": "empty:",
        "persist-js": "empty:",
        "react-bootstrap": "empty:",
        "react-dom": "empty:",
        "react-prop-types": "empty:",
        "react-redux": "empty:",
        "react": "empty:",
        "redux-thunk": "empty:",
        "redux": "empty:",
        "requirejs": "empty:",
        "reselect": "empty:",
        "select2": "empty:",
        "sinon": "empty:",
        "sprintf": "empty:",
        "underscore": "empty:"
      }
    }
  },
  "navbar": {
    "options": {
      "logLevel": 1,
      "baseUrl": "build",
      "name": "navbar.bundle",
      "out": "build/navbar.bundle.js",
      "optimize": "none",
      "mainConfigFile": "build/app.config.js",
      "deps": [],
      "create": true,
      "include": [
        "js/widgets/navbar/widget"
      ],
      "exclude": [
        "common.bundle",
        "core.bundle"
      ],
      "paths": {
        "backbone-validation": "empty:",
        "backbone.stickit": "empty:",
        "backbone.wreqr": "empty:",
        "backbone": "empty:",
        "bootstrap": "empty:",
        "classnames": "empty:",
        "clipboard": "empty:",
        "create-react-class": "empty:",
        "d3-cloud": "empty:",
        "d3": "empty:",
        "es5-shim": "empty:",
        "filesaver": "empty:",
        "google-analytics": "empty:",
        "google-recaptcha": "empty:",
        "jquery-ui": "empty:",
        "jquery": "empty:",
        "jsonpath": "empty:",
        "marionette": "empty:",
        "mathjax": "empty:",
        "moment": "empty:",
        "persist-js": "empty:",
        "react-bootstrap": "empty:",
        "react-dom": "empty:",
        "react-prop-types": "empty:",
        "react-redux": "empty:",
        "react": "empty:",
        "redux-thunk": "empty:",
        "redux": "empty:",
        "requirejs": "empty:",
        "reselect": "empty:",
        "select2": "empty:",
        "sinon": "empty:",
        "sprintf": "empty:",
        "underscore": "empty:"
      }
    }
  },
  "orcid-selector": {
    "options": {
      "logLevel": 1,
      "baseUrl": "build",
      "name": "orcid-selector.bundle",
      "out": "build/orcid-selector.bundle.js",
      "optimize": "none",
      "mainConfigFile": "build/app.config.js",
      "deps": [],
      "create": true,
      "include": [
        "es6!js/widgets/orcid-selector/widget.jsx"
      ],
      "exclude": [
        "common.bundle",
        "core.bundle"
      ],
      "paths": {
        "backbone-validation": "empty:",
        "backbone.stickit": "empty:",
        "backbone.wreqr": "empty:",
        "backbone": "empty:",
        "bootstrap": "empty:",
        "classnames": "empty:",
        "clipboard": "empty:",
        "create-react-class": "empty:",
        "d3-cloud": "empty:",
        "d3": "empty:",
        "es5-shim": "empty:",
        "filesaver": "empty:",
        "google-analytics": "empty:",
        "google-recaptcha": "empty:",
        "jquery-ui": "empty:",
        "jquery": "empty:",
        "jsonpath": "empty:",
        "marionette": "empty:",
        "mathjax": "empty:",
        "moment": "empty:",
        "persist-js": "empty:",
        "react-bootstrap": "empty:",
        "react-dom": "empty:",
        "react-prop-types": "empty:",
        "react-redux": "empty:",
        "react": "empty:",
        "redux-thunk": "empty:",
        "redux": "empty:",
        "requirejs": "empty:",
        "reselect": "empty:",
        "select2": "empty:",
        "sinon": "empty:",
        "sprintf": "empty:",
        "underscore": "empty:"
      }
    }
  },
  "paper_search_form": {
    "options": {
      "logLevel": 1,
      "baseUrl": "build",
      "name": "paper_search_form.bundle",
      "out": "build/paper_search_form.bundle.js",
      "optimize": "none",
      "mainConfigFile": "build/app.config.js",
      "deps": [],
      "create": true,
      "include": [
        "js/widgets/paper_search_form/widget"
      ],
      "exclude": [
        "common.bundle",
        "core.bundle"
      ],
      "paths": {
        "backbone-validation": "empty:",
        "backbone.stickit": "empty:",
        "backbone.wreqr": "empty:",
        "backbone": "empty:",
        "bootstrap": "empty:",
        "classnames": "empty:",
        "clipboard": "empty:",
        "create-react-class": "empty:",
        "d3-cloud": "empty:",
        "d3": "empty:",
        "es5-shim": "empty:",
        "filesaver": "empty:",
        "google-analytics": "empty:",
        "google-recaptcha": "empty:",
        "jquery-ui": "empty:",
        "jquery": "empty:",
        "jsonpath": "empty:",
        "marionette": "empty:",
        "mathjax": "empty:",
        "moment": "empty:",
        "persist-js": "empty:",
        "react-bootstrap": "empty:",
        "react-dom": "empty:",
        "react-prop-types": "empty:",
        "react-redux": "empty:",
        "react": "empty:",
        "redux-thunk": "empty:",
        "redux": "empty:",
        "requirejs": "empty:",
        "reselect": "empty:",
        "select2": "empty:",
        "sinon": "empty:",
        "sprintf": "empty:",
        "underscore": "empty:"
      }
    }
  },
  "preferences": {
    "options": {
      "logLevel": 1,
      "baseUrl": "build",
      "name": "preferences.bundle",
      "out": "build/preferences.bundle.js",
      "optimize": "none",
      "mainConfigFile": "build/app.config.js",
      "deps": [],
      "create": true,
      "include": [
        "js/widgets/preferences/widget"
      ],
      "exclude": [
        "common.bundle",
        "core.bundle"
      ],
      "paths": {
        "backbone-validation": "empty:",
        "backbone.stickit": "empty:",
        "backbone.wreqr": "empty:",
        "backbone": "empty:",
        "bootstrap": "empty:",
        "classnames": "empty:",
        "clipboard": "empty:",
        "create-react-class": "empty:",
        "d3-cloud": "empty:",
        "d3": "empty:",
        "es5-shim": "empty:",
        "filesaver": "empty:",
        "google-analytics": "empty:",
        "google-recaptcha": "empty:",
        "jquery-ui": "empty:",
        "jquery": "empty:",
        "jsonpath": "empty:",
        "marionette": "empty:",
        "mathjax": "empty:",
        "moment": "empty:",
        "persist-js": "empty:",
        "react-bootstrap": "empty:",
        "react-dom": "empty:",
        "react-prop-types": "empty:",
        "react-redux": "empty:",
        "react": "empty:",
        "redux-thunk": "empty:",
        "redux": "empty:",
        "requirejs": "empty:",
        "reselect": "empty:",
        "select2": "empty:",
        "sinon": "empty:",
        "sprintf": "empty:",
        "underscore": "empty:"
      }
    }
  },
  "recommender": {
    "options": {
      "logLevel": 1,
      "baseUrl": "build",
      "name": "recommender.bundle",
      "out": "build/recommender.bundle.js",
      "optimize": "none",
      "mainConfigFile": "build/app.config.js",
      "deps": [],
      "create": true,
      "include": [
        "js/widgets/recommender/widget"
      ],
      "exclude": [
        "common.bundle",
        "core.bundle"
      ],
      "paths": {
        "backbone-validation": "empty:",
        "backbone.stickit": "empty:",
        "backbone.wreqr": "empty:",
        "backbone": "empty:",
        "bootstrap": "empty:",
        "classnames": "empty:",
        "clipboard": "empty:",
        "create-react-class": "empty:",
        "d3-cloud": "empty:",
        "d3": "empty:",
        "es5-shim": "empty:",
        "filesaver": "empty:",
        "google-analytics": "empty:",
        "google-recaptcha": "empty:",
        "jquery-ui": "empty:",
        "jquery": "empty:",
        "jsonpath": "empty:",
        "marionette": "empty:",
        "mathjax": "empty:",
        "moment": "empty:",
        "persist-js": "empty:",
        "react-bootstrap": "empty:",
        "react-dom": "empty:",
        "react-prop-types": "empty:",
        "react-redux": "empty:",
        "react": "empty:",
        "redux-thunk": "empty:",
        "redux": "empty:",
        "requirejs": "empty:",
        "reselect": "empty:",
        "select2": "empty:",
        "sinon": "empty:",
        "sprintf": "empty:",
        "underscore": "empty:"
      }
    }
  },
  "resources": {
    "options": {
      "logLevel": 1,
      "baseUrl": "build",
      "name": "resources.bundle",
      "out": "build/resources.bundle.js",
      "optimize": "none",
      "mainConfigFile": "build/app.config.js",
      "deps": [],
      "create": true,
      "include": [
        "es6!js/widgets/resources/widget.jsx"
      ],
      "exclude": [
        "common.bundle",
        "core.bundle"
      ],
      "paths": {
        "backbone-validation": "empty:",
        "backbone.stickit": "empty:",
        "backbone.wreqr": "empty:",
        "backbone": "empty:",
        "bootstrap": "empty:",
        "classnames": "empty:",
        "clipboard": "empty:",
        "create-react-class": "empty:",
        "d3-cloud": "empty:",
        "d3": "empty:",
        "es5-shim": "empty:",
        "filesaver": "empty:",
        "google-analytics": "empty:",
        "google-recaptcha": "empty:",
        "jquery-ui": "empty:",
        "jquery": "empty:",
        "jsonpath": "empty:",
        "marionette": "empty:",
        "mathjax": "empty:",
        "moment": "empty:",
        "persist-js": "empty:",
        "react-bootstrap": "empty:",
        "react-dom": "empty:",
        "react-prop-types": "empty:",
        "react-redux": "empty:",
        "react": "empty:",
        "redux-thunk": "empty:",
        "redux": "empty:",
        "requirejs": "empty:",
        "reselect": "empty:",
        "select2": "empty:",
        "sinon": "empty:",
        "sprintf": "empty:",
        "underscore": "empty:"
      }
    }
  },
  "results": {
    "options": {
      "logLevel": 1,
      "baseUrl": "build",
      "name": "results.bundle",
      "out": "build/results.bundle.js",
      "optimize": "none",
      "mainConfigFile": "build/app.config.js",
      "deps": [],
      "create": true,
      "include": [
        "js/widgets/results/widget"
      ],
      "exclude": [
        "common.bundle",
        "core.bundle"
      ],
      "paths": {
        "backbone-validation": "empty:",
        "backbone.stickit": "empty:",
        "backbone.wreqr": "empty:",
        "backbone": "empty:",
        "bootstrap": "empty:",
        "classnames": "empty:",
        "clipboard": "empty:",
        "create-react-class": "empty:",
        "d3-cloud": "empty:",
        "d3": "empty:",
        "es5-shim": "empty:",
        "filesaver": "empty:",
        "google-analytics": "empty:",
        "google-recaptcha": "empty:",
        "jquery-ui": "empty:",
        "jquery": "empty:",
        "jsonpath": "empty:",
        "marionette": "empty:",
        "mathjax": "empty:",
        "moment": "empty:",
        "persist-js": "empty:",
        "react-bootstrap": "empty:",
        "react-dom": "empty:",
        "react-prop-types": "empty:",
        "react-redux": "empty:",
        "react": "empty:",
        "redux-thunk": "empty:",
        "redux": "empty:",
        "requirejs": "empty:",
        "reselect": "empty:",
        "select2": "empty:",
        "sinon": "empty:",
        "sprintf": "empty:",
        "underscore": "empty:"
      }
    }
  },
  "sort": {
    "options": {
      "logLevel": 1,
      "baseUrl": "build",
      "name": "sort.bundle",
      "out": "build/sort.bundle.js",
      "optimize": "none",
      "mainConfigFile": "build/app.config.js",
      "deps": [],
      "create": true,
      "include": [
        "es6!js/widgets/sort/widget.jsx"
      ],
      "exclude": [
        "common.bundle",
        "core.bundle"
      ],
      "paths": {
        "backbone-validation": "empty:",
        "backbone.stickit": "empty:",
        "backbone.wreqr": "empty:",
        "backbone": "empty:",
        "bootstrap": "empty:",
        "classnames": "empty:",
        "clipboard": "empty:",
        "create-react-class": "empty:",
        "d3-cloud": "empty:",
        "d3": "empty:",
        "es5-shim": "empty:",
        "filesaver": "empty:",
        "google-analytics": "empty:",
        "google-recaptcha": "empty:",
        "jquery-ui": "empty:",
        "jquery": "empty:",
        "jsonpath": "empty:",
        "marionette": "empty:",
        "mathjax": "empty:",
        "moment": "empty:",
        "persist-js": "empty:",
        "react-bootstrap": "empty:",
        "react-dom": "empty:",
        "react-prop-types": "empty:",
        "react-redux": "empty:",
        "react": "empty:",
        "redux-thunk": "empty:",
        "redux": "empty:",
        "requirejs": "empty:",
        "reselect": "empty:",
        "select2": "empty:",
        "sinon": "empty:",
        "sprintf": "empty:",
        "underscore": "empty:"
      }
    }
  },
  "user_navbar": {
    "options": {
      "logLevel": 1,
      "baseUrl": "build",
      "name": "user_navbar.bundle",
      "out": "build/user_navbar.bundle.js",
      "optimize": "none",
      "mainConfigFile": "build/app.config.js",
      "deps": [],
      "create": true,
      "include": [
        "js/widgets/user_navbar/widget"
      ],
      "exclude": [
        "common.bundle",
        "core.bundle"
      ],
      "paths": {
        "backbone-validation": "empty:",
        "backbone.stickit": "empty:",
        "backbone.wreqr": "empty:",
        "backbone": "empty:",
        "bootstrap": "empty:",
        "classnames": "empty:",
        "clipboard": "empty:",
        "create-react-class": "empty:",
        "d3-cloud": "empty:",
        "d3": "empty:",
        "es5-shim": "empty:",
        "filesaver": "empty:",
        "google-analytics": "empty:",
        "google-recaptcha": "empty:",
        "jquery-ui": "empty:",
        "jquery": "empty:",
        "jsonpath": "empty:",
        "marionette": "empty:",
        "mathjax": "empty:",
        "moment": "empty:",
        "persist-js": "empty:",
        "react-bootstrap": "empty:",
        "react-dom": "empty:",
        "react-prop-types": "empty:",
        "react-redux": "empty:",
        "react": "empty:",
        "redux-thunk": "empty:",
        "redux": "empty:",
        "requirejs": "empty:",
        "reselect": "empty:",
        "select2": "empty:",
        "sinon": "empty:",
        "sprintf": "empty:",
        "underscore": "empty:"
      }
    }
  },
  "user_settings": {
    "options": {
      "logLevel": 1,
      "baseUrl": "build",
      "name": "user_settings.bundle",
      "out": "build/user_settings.bundle.js",
      "optimize": "none",
      "mainConfigFile": "build/app.config.js",
      "deps": [],
      "create": true,
      "include": [
        "js/widgets/user_settings/widget"
      ],
      "exclude": [
        "common.bundle",
        "core.bundle"
      ],
      "paths": {
        "backbone-validation": "empty:",
        "backbone.stickit": "empty:",
        "backbone.wreqr": "empty:",
        "backbone": "empty:",
        "bootstrap": "empty:",
        "classnames": "empty:",
        "clipboard": "empty:",
        "create-react-class": "empty:",
        "d3-cloud": "empty:",
        "d3": "empty:",
        "es5-shim": "empty:",
        "filesaver": "empty:",
        "google-analytics": "empty:",
        "google-recaptcha": "empty:",
        "jquery-ui": "empty:",
        "jquery": "empty:",
        "jsonpath": "empty:",
        "marionette": "empty:",
        "mathjax": "empty:",
        "moment": "empty:",
        "persist-js": "empty:",
        "react-bootstrap": "empty:",
        "react-dom": "empty:",
        "react-prop-types": "empty:",
        "react-redux": "empty:",
        "react": "empty:",
        "redux-thunk": "empty:",
        "redux": "empty:",
        "requirejs": "empty:",
        "reselect": "empty:",
        "select2": "empty:",
        "sinon": "empty:",
        "sprintf": "empty:",
        "underscore": "empty:"
      }
    }
  },
  "wordcloud": {
    "options": {
      "logLevel": 1,
      "baseUrl": "build",
      "name": "wordcloud.bundle",
      "out": "build/wordcloud.bundle.js",
      "optimize": "none",
      "mainConfigFile": "build/app.config.js",
      "deps": [],
      "create": true,
      "include": [
        "js/widgets/wordcloud/widget"
      ],
      "exclude": [
        "common.bundle",
        "core.bundle"
      ],
      "paths": {
        "backbone-validation": "empty:",
        "backbone.stickit": "empty:",
        "backbone.wreqr": "empty:",
        "backbone": "empty:",
        "bootstrap": "empty:",
        "classnames": "empty:",
        "clipboard": "empty:",
        "create-react-class": "empty:",
        "d3-cloud": "empty:",
        "d3": "empty:",
        "es5-shim": "empty:",
        "filesaver": "empty:",
        "google-analytics": "empty:",
        "google-recaptcha": "empty:",
        "jquery-ui": "empty:",
        "jquery": "empty:",
        "jsonpath": "empty:",
        "marionette": "empty:",
        "mathjax": "empty:",
        "moment": "empty:",
        "persist-js": "empty:",
        "react-bootstrap": "empty:",
        "react-dom": "empty:",
        "react-prop-types": "empty:",
        "react-redux": "empty:",
        "react": "empty:",
        "redux-thunk": "empty:",
        "redux": "empty:",
        "requirejs": "empty:",
        "reselect": "empty:",
        "select2": "empty:",
        "sinon": "empty:",
        "sprintf": "empty:",
        "underscore": "empty:"
      }
    }
  }
};