// GENERATED FILE (edits will be overwritten)

module.exports =
{
  "analytics": {
    "options": {
      "waitSeconds": 0,
      "logLevel": 1,
      "baseUrl": "src",
      "optimize": "none",
      "mainConfigFile": "src/discovery.config.js",
      "deps": [],
      "stubModules": [
        "babel",
        "es6"
      ],
      "create": true,
      "paths": {
        "backbone-validation": "empty:",
        "backbone.stickit": "empty:",
        "backbone.wreqr": "empty:",
        "backbone": "empty:",
        "bootstrap": "empty:",
        "classnames": "empty:",
        "clipboard": "empty:",
        "create-react-class": "empty:",
        "d3-cloud": "empty:",
        "d3": "empty:",
        "es5-shim": "empty:",
        "filesaver": "empty:",
        "google-analytics": "empty:",
        "google-recaptcha": "empty:",
        "jquery-ui": "empty:",
        "jsonpath": "empty:",
        "marionette": "empty:",
        "mathjax": "empty:",
        "moment": "empty:",
        "persist-js": "empty:",
        "react-bootstrap": "empty:",
        "react-dom": "empty:",
        "react-prop-types": "empty:",
        "react-redux": "empty:",
        "react": "empty:",
        "redux-thunk": "empty:",
        "redux": "empty:",
        "requirejs": "empty:",
        "reselect": "empty:",
        "select2": "empty:",
        "sinon": "empty:",
        "sprintf": "empty:",
        "underscore": "empty:"
      },
      "name": "analytics.bundle",
      "out": "build/analytics.bundle.js",
      "include": [
        "analytics"
      ]
    }
  },
  "app": {
    "options": {
      "waitSeconds": 0,
      "logLevel": 1,
      "baseUrl": "src",
      "optimize": "none",
      "mainConfigFile": "src/discovery.config.js",
      "deps": [],
      "stubModules": [
        "babel",
        "es6"
      ],
      "create": true,
      "paths": {
        "backbone-validation": "empty:",
        "backbone.stickit": "empty:",
        "backbone.wreqr": "empty:",
        "backbone": "empty:",
        "bootstrap": "empty:",
        "classnames": "empty:",
        "clipboard": "empty:",
        "create-react-class": "empty:",
        "d3-cloud": "empty:",
        "d3": "empty:",
        "es5-shim": "empty:",
        "filesaver": "empty:",
        "google-analytics": "empty:",
        "google-recaptcha": "empty:",
        "jquery-ui": "empty:",
        "jsonpath": "empty:",
        "marionette": "empty:",
        "mathjax": "empty:",
        "moment": "empty:",
        "persist-js": "empty:",
        "react-bootstrap": "empty:",
        "react-dom": "empty:",
        "react-prop-types": "empty:",
        "react-redux": "empty:",
        "react": "empty:",
        "redux-thunk": "empty:",
        "redux": "empty:",
        "requirejs": "empty:",
        "reselect": "empty:",
        "select2": "empty:",
        "sinon": "empty:",
        "sprintf": "empty:",
        "underscore": "empty:"
      },
      "name": "app.bundle",
      "out": "build/app.bundle.js",
      "include": [
        "router",
        "discovery.vars",
        "js/apps/discovery/main",
        "async",
        "cache",
        "babel",
        "es6",
        "hbs",
        "immutable",
        "jquery",
        "jquery-querybuilder",
        "mocha",
        "redux-immutable",
        "utils",
        "js/apps/discovery/main",
        "js/apps/discovery/navigator",
        "js/components/alerts_mediator",
        "js/components/alerts",
        "js/components/api_feedback",
        "js/components/api_query_updater",
        "js/components/api_query",
        "js/components/api_request_queue",
        "js/components/api_request",
        "js/components/api_response",
        "js/components/api_targets",
        "js/components/app_storage",
        "js/components/application",
        "js/components/beehive",
        "js/components/csrf_manager",
        "js/components/default_request",
        "js/components/doc_stash_controller",
        "js/components/facade",
        "js/components/feedback_mediator",
        "js/components/generic_module",
        "js/components/history_manager",
        "js/components/json_response",
        "js/components/library_controller",
        "js/components/multi_params",
        "js/components/navigator",
        "js/components/paginator",
        "js/components/persistent_storage",
        "js/components/pubsub_events",
        "js/components/pubsub_key",
        "js/components/query_builder/plugin",
        "js/components/query_builder/rules_translator",
        "js/components/query_mediator",
        "js/components/query_validator",
        "js/components/recaptcha_manager",
        "js/components/services_container",
        "js/components/session",
        "js/components/solr_params",
        "js/components/solr_response",
        "js/components/transition_catalog",
        "js/components/transition",
        "js/components/user",
        "js/mixins/add_secondary_sort",
        "js/mixins/add_stable_index_to_collection",
        "js/mixins/api_access",
        "js/mixins/dependon",
        "js/mixins/discovery_bootstrap",
        "js/mixins/form_view_functions",
        "js/mixins/formatter",
        "js/mixins/hardened",
        "js/mixins/link_generator_mixin",
        "js/mixins/openurl_generator",
        "js/mixins/papers_utils",
        "js/mixins/user_change_rows",
        "js/mixins/widget_mixin_method",
        "js/mixins/widget_pagination",
        "js/mixins/widget_state_manager",
        "js/mixins/widget_utility",
        "js/modules/hello",
        "js/modules/orcid/extension",
        "js/modules/orcid/item_view_extension",
        "js/modules/orcid/module",
        "js/modules/orcid/orcid_api",
        "js/modules/orcid/profile",
        "js/modules/orcid/widget/widget",
        "js/modules/orcid/work",
        "js/bugutils/diagnostics",
        "js/bugutils/minimal_pubsub",
        "js/page_managers/controller",
        "js/page_managers/master",
        "js/page_managers/one_column_view",
        "js/page_managers/three_column_view",
        "js/page_managers/toc_controller",
        "js/page_managers/toc_widget",
        "js/page_managers/view_mixin",
        "js/services/api",
        "js/services/default_pubsub",
        "js/services/pubsub",
        "js/services/storage",
        "js/widgets/abstract/widget",
        "js/widgets/alerts/widget",
        "js/widgets/api_query/widget",
        "js/widgets/api_request/widget",
        "js/widgets/api_response/widget",
        "es6!js/widgets/associated/widget.jsx",
        "js/widgets/authentication/widget",
        "es6!js/widgets/author_affiliation_tool/widget.jsx",
        "js/widgets/base/base_widget",
        "js/widgets/breadcrumb/widget",
        "js/widgets/bubble_chart/widget",
        "js/widgets/citation_helper/widget",
        "js/widgets/classic_form/widget",
        "js/widgets/dropdown-menu/widget",
        "es6!js/widgets/export/widget.jsx",
        "js/widgets/facet/graph-facet/widget",
        "js/widgets/facet/widget",
        "js/widgets/filter_visualizer/widget",
        "js/widgets/footer/widget",
        "js/widgets/graphics/widget",
        "js/widgets/green_button/widget",
        "js/widgets/libraries_all/widget",
        "js/widgets/library_import/widget",
        "js/widgets/library_individual/widget",
        "js/widgets/library_list/widget",
        "js/widgets/list_of_things/details_widget",
        "js/widgets/list_of_things/widget",
        "js/widgets/loading/widget",
        "js/widgets/meta_tags/widget",
        "js/widgets/metrics/widget",
        "js/widgets/navbar/widget",
        "js/widgets/network_vis/network_widget",
        "es6!js/widgets/orcid-selector/widget.jsx",
        "js/widgets/paper_search_form/widget",
        "js/widgets/preferences/widget",
        "js/widgets/query_info/query_info_widget",
        "js/widgets/recommender/widget",
        "es6!js/widgets/resources/widget.jsx",
        "js/widgets/results/widget",
        "js/widgets/search_bar/search_bar_widget",
        "es6!js/widgets/sort/widget.jsx",
        "js/widgets/tabs/tabs_widget",
        "js/widgets/user_navbar/widget",
        "js/widgets/user_settings/widget",
        "js/widgets/wordcloud/widget",
        "js/wraps/abstract_page_library_add/widget",
        "js/wraps/abstract_page_manager/abstract_page_manager",
        "js/wraps/affiliation_facet",
        "js/wraps/alerts_mediator",
        "js/wraps/authentication_page_manager",
        "js/wraps/author_facet",
        "js/wraps/author_network",
        "js/wraps/bibgroup_facet",
        "js/wraps/bibstem_facet",
        "js/wraps/citations",
        "js/wraps/coreads",
        "js/wraps/data_facet",
        "js/wraps/database_facet",
        "js/wraps/discovery_mediator",
        "js/wraps/error_page_manager/error_page_manager",
        "js/wraps/export_dropdown",
        "js/wraps/grants_facet",
        "js/wraps/graph_tabs",
        "js/wraps/home_page_manager/home_page_manager",
        "js/wraps/keyword_facet",
        "js/wraps/landing_page_manager/landing_page_manager",
        "js/wraps/libraries_page_manager/libraries_page_manager",
        "js/wraps/ned_object_facet",
        "js/wraps/orcid_page_manager",
        "js/wraps/orcid_page_manager/orcid_page_manager",
        "js/wraps/orcid-instructions-page-manager/manager",
        "js/wraps/paper_export",
        "js/wraps/paper_metrics",
        "js/wraps/paper_network",
        "js/wraps/public_libraries_page_manager/public_libraries_manager",
        "js/wraps/pubtype_facet",
        "js/wraps/refereed_facet",
        "js/wraps/references",
        "js/wraps/results_page_manager",
        "js/wraps/sidebar-graphics-widget",
        "js/wraps/simbad_object_facet",
        "js/wraps/table_of_contents",
        "js/wraps/user_settings_page_manager/user_page_manager",
        "js/wraps/visualization_dropdown",
        "js/wraps/vizier_facet"
      ],
      "exclude": [
        "analytics"
      ]
    }
  }
};